AllCops:
  Exclude: 
    - 'db/**/*'
    - 'tmp/**/*'

Bundler/OrderedGems:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'features/**/*'

Metrics/LineLength:
  Enabled: false
  
Metrics/MethodLength:
  Max: 20

Style/FrozenStringLiteralComment:
  Exclude:
    - db/**/*
    - config/rufus.d/**/*
    - '**/*.rabl'

Style/SymbolArray:
  Enabled: false

Style/Documentation:
  Enabled: false
