AllCops:
  Exclude: 
    - 'db/**/*'
    - 'tmp/**/*'

Bundler/OrderedGems:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
  
Layout/SpaceBeforeBlockBraces:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'features/**/*'
  ExcludedMethods:
    - refine
    - state_machine

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*'

Metrics/ParameterLists:
  CountKeywordArgs: false

Style/FrozenStringLiteralComment:
  Exclude:
    - db/**/*
    - config/rufus.d/**/*
    - '**/*.rabl'

Style/RegexpLiteral:
  AllowInnerSlashes: true

Style/SymbolArray:
  Enabled: false

Style/Documentation:
  Enabled: false
  
Style/Lambda:
  EnforcedStyle: literal
